# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: vpn

config: 
  interface: 
    address: "10.100.200.1/24"
    port: 51820
    privatekey: "sNQQX5MURQrLp6jthxQmDSUGYcPilJHnuzqJIlx3l1w="

  # peers: []
  peers: 
  - publickey: "0oqojqQvGR9OIGG/L7yXBrOqzQrDkQiIAh7zw0F0tC8="
    allowedips: 10.100.200.2/32
    name: Foo 
  - publickey: "7dCTaAJQw2CZr/PJhaLHvjFcOwkWkvfPc6JnZV/bUSM="
    allowedips: 10.100.200.3/32
    name: Bar


wireguard: 
  image:
    repository: eftechcombr/wireguard
    pullPolicy: IfNotPresent
    tag: "latest"

initcontainer: 
  image: 
    repository: busybox
    tag: "1.32.0"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
  # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#Options: NodePort, LoadBalancer
services:
  type: NodePort
  port: 31820
  protocol: UDP

livenessProbe:
  httpGet:
    path: /
    port: 8080
readinessProbe:
  httpGet:
    path: /
    port: 8080
