apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.services.type | default "NodePort" }}
  # type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.services.port }}
    targetPort: {{ .Values.config.interface.port }}
    nodePort: {{ .Values.services.port }}
    protocol: {{ .Values.services.protocol }}
