apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace | default "vpn" }}
data:
  wg0.conf: |
    [Interface]
    Address = {{ .Values.config.interface.address | default "10.245.245.1/24" }}
    ListenPort = {{ .Values.config.interface.port | default "51820" }}
    PostUp = wg set wg0 private-key /etc/wireguard/wg0.key && iptables -t nat -A POSTROUTING -s {{ .Values.config.interface.address | replace "1/24" "0/24" }} -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -s {{ .Values.config.interface.address | replace "1/24" "0/24" }} -o eth0 -j MASQUERADE
    #
    {{- range $peer := .Values.config.peers }} 
    #
    # name: {{ $peer.name | replace " " "-" }}
    [Peer]
    PublicKey = {{ $peer.publickey }}
    AllowedIPs = {{ $peer.allowedips }} 
    #{{ end }}

